name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc-14 \
          g++-14 \
          build-essential \
          cmake \
          libgl1-mesa-dev \
          libgtest-dev

    - name: Check Qt modules
      run: |
        python3 -m pip install aqtinstall
        aqt list-qt linux desktop --modules 6.9.1 linux_gcc_64

    - name: Install Qt 6.9.1
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.9.1'
        host: 'linux'
        target: 'desktop'
        arch: 'linux_gcc_64'
        cache: true

    - name: Configure CMake
      run: |
        cmake -S . -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_COMPILER=gcc-14 \
          -DCMAKE_CXX_COMPILER=g++-14

    - name: Build
      run: cmake --build build --parallel $(nproc)

    - name: Run Tests
      run: ctest --test-dir build --output-on-failure
